### PR TITLE
Emoji kitchen update

### PR DESCRIPTION
**Pull request by w4v3**
I updated the repo to include the new stickers that are available since Dec 2021. I also added an html gallery to be able to browse all stickers in a systematic fashion. It can be viewed using GitHub Pages at https://w4v3.github.io/Google-Sticker-Mashup-Research.

### CODE REVIEW

**Comment by UCYT5040** [comment]
Reviewing...
Will add Gh pages here when if I decide to merge.

**Comment by UCYT5040** [comment]
Thanks for your contributions. I will update these on the sticker vote site too

**Comment by w4v3** [comment]
To make the pages work, you don't need to use a dedicated branch anymore. Under Settings > Pages, you can just set the source to `main` branch and `/ (root)` directory.

**Comment by UCYT5040** [comment]
I didn't realize you had an index.html (and I should have looked for that)
Fixing it...

**Comment by w4v3** [comment]
Some images seem to be broken (more than should be). It should work if you just use the `../stickers/` in front of every img url.

**Comment by UCYT5040** [comment]
Oh right, forgot I changed that. Sorry I messed this up

**Comment by w4v3** [comment]
No worries! By the way, when I initially was looking for something like this repo, it took me a really long time to find it, probably because it doesn't say "emoji kitchen" anywhere, which is the official name of the feature. So if visibility is one of your goals then it might be a good idea to mention that name somewhere :)

**Comment by UCYT5040** [comment]
Right, I didn't know that name originally so I name it this.

Since you seem to know a lot more about GitHub than I, I'm gonna add you as a collaborator.

**Pull request merged**
